services:
  - type: web
    name: hackrx-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: API_ACCESS_TOKEN
        sync: false
      - key: PORT
        value: 10000
    scaling:
      minInstances: 1
      maxInstances: 1